#!/bin/bash
# This script autogenerated by DownloadEnwikiDump.ipynb

echo "Starting download." && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p908307p926788.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p908307p926788.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p908307p926788.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1238233p1259025.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1238233p1259025.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1238233p1259025.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1791080p1819527.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1791080p1819527.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1791080p1819527.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p678432p692313.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p678432p692313.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p678432p692313.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2609274p2644545.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2609274p2644545.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2609274p2644545.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2456308p2492848.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2456308p2492848.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2456308p2492848.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p708168p725430.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p708168p725430.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p708168p725430.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1636469p1659572.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1636469p1659572.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1636469p1659572.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2644546p2682830.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2644546p2682830.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2644546p2682830.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2257118p2288995.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2257118p2288995.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2257118p2288995.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p633556p647847.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p633556p647847.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p633556p647847.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1407553p1434810.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1407553p1434810.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1407553p1434810.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1376851p1407552.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1376851p1407552.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1376851p1407552.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1147819p1171938.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1147819p1171938.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1147819p1171938.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p759523p779496.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p759523p779496.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p759523p779496.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1499207p1528725.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1499207p1528725.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1499207p1528725.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p892914p908306.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p892914p908306.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p892914p908306.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952685p1981111.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1952685p1981111.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952685p1981111.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p946363p965149.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p946363p965149.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p946363p965149.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2429464p2456307.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2429464p2456307.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2429464p2456307.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1659573p1683639.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1659573p1683639.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1659573p1683639.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2863182p2902893.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2863182p2902893.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2863182p2902893.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p598398p609831.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p598398p609831.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p598398p609831.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p565314p573310.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p565314p573310.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p565314p573310.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1819528p1848546.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1819528p1848546.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1819528p1848546.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1470402p1499206.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1470402p1499206.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1470402p1499206.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2988240p3031715.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2988240p3031715.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2988240p3031715.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2197116p2229273.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2197116p2229273.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2197116p2229273.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2145968p2174594.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2145968p2174594.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2145968p2174594.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2945099p2988239.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2945099p2988239.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2945099p2988239.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p889149p892912.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p889149p892912.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p889149p892912.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1171939p1195788.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1171939p1195788.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1171939p1195788.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1708688p1739088.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1708688p1739088.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1708688p1739088.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p972028p972088.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p972028p972088.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p972028p972088.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2575569p2609273.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2575569p2609273.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2575569p2609273.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1981112p2012549.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1981112p2012549.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1981112p2012549.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p692314p708167.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p692314p708167.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p692314p708167.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1584614p1609729.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1584614p1609729.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1584614p1609729.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1904539p1933771.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1904539p1933771.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1904539p1933771.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1127545p1147818.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1127545p1147818.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1127545p1147818.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1007213p1025027.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1007213p1025027.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1007213p1025027.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2174595p2197115.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2174595p2197115.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2174595p2197115.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2366755p2399244.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2366755p2399244.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2366755p2399244.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p647848p662782.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p647848p662782.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p647848p662782.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2822193p2863181.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2822193p2863181.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2822193p2863181.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2682831p2729088.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2682831p2729088.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2682831p2729088.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p3031716p3046511.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p3031716p3046511.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p3031716p3046511.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1085285p1107100.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1085285p1107100.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1085285p1107100.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1349036p1376850.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1349036p1376850.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1349036p1376850.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p584048p598397.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p584048p598397.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p584048p598397.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p926789p946362.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p926789p946362.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p926789p946362.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1560273p1584613.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1560273p1584613.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1560273p1584613.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535836p2535859.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2535836p2535859.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535836p2535859.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p804816p839411.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p804816p839411.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p804816p839411.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1195789p1218022.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1195789p1218022.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1195789p1218022.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p725431p741848.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p725431p741848.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p725431p741848.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p965150p971992.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p965150p971992.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p965150p971992.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1218023p1238232.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1218023p1238232.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1218023p1238232.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1528726p1560272.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1528726p1560272.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1528726p1560272.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1683640p1708687.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1683640p1708687.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1683640p1708687.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1460926p1469573.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1460926p1469573.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1460926p1469573.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p856132p872910.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p856132p872910.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p856132p872910.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1043762p1063042.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1043762p1063042.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1043762p1063042.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535860p2535885.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2535860p2535885.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535860p2535885.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p972089p986136.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p972089p986136.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p972089p986136.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535886p2536120.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2535886p2536120.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535886p2536120.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1768746p1791079.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1768746p1791079.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1768746p1791079.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1848547p1875437.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1848547p1875437.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1848547p1875437.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2399245p2429463.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2399245p2429463.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2399245p2429463.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2046428p2077275.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2046428p2077275.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2046428p2077275.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1469574p1470401.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1469574p1470401.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1469574p1470401.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2729089p2777893.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2729089p2777893.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2729089p2777893.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2320672p2336422.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2320672p2336422.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2320672p2336422.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p609832p622695.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p609832p622695.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p609832p622695.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1933772p1952650.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1933772p1952650.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1933772p1952650.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1434811p1460925.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1434811p1460925.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1434811p1460925.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1107101p1127544.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1107101p1127544.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1107101p1127544.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p986137p990328.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p986137p990328.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p986137p990328.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p741849p759522.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p741849p759522.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p741849p759522.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535154p2535757.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2535154p2535757.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535154p2535757.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1739089p1768745.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1739089p1768745.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1739089p1768745.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2110920p2145967.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2110920p2145967.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2110920p2145967.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2777894p2822192.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2777894p2822192.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2777894p2822192.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1294863p1323649.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1294863p1323649.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1294863p1323649.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p622696p633555.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p622696p633555.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p622696p633555.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2288996p2320671.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2288996p2320671.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2288996p2320671.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2492849p2525520.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2492849p2525520.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2492849p2525520.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952668p1952684.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1952668p1952684.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952668p1952684.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p779497p804815.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p779497p804815.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p779497p804815.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1259026p1268691.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1259026p1268691.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1259026p1268691.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p990329p1007212.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p990329p1007212.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p990329p1007212.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2525521p2535153.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2525521p2535153.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2525521p2535153.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2336425p2366754.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2336425p2366754.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2336425p2366754.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1609730p1636468.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1609730p1636468.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1609730p1636468.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1323650p1349035.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1323650p1349035.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1323650p1349035.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p971993p972027.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p971993p972027.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p971993p972027.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2536121p2575568.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2536121p2575568.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2536121p2575568.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1025028p1043761.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1025028p1043761.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1025028p1043761.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1875438p1904538.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1875438p1904538.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1875438p1904538.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2229274p2257117.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2229274p2257117.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2229274p2257117.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952651p1952667.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p1952651p1952667.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p1952651p1952667.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2077276p2110919.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2077276p2110919.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2077276p2110919.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2012550p2046427.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history9.xml-p2012550p2046427.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history9.xml-p2012550p2046427.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1063043p1085284.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history7.xml-p1063043p1085284.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history7.xml-p1063043p1085284.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535758p2535835.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2535758p2535835.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2535758p2535835.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p573311p584047.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p573311p584047.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p573311p584047.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p839412p856131.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p839412p856131.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p839412p856131.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1268692p1294862.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history8.xml-p1268692p1294862.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history8.xml-p1268692p1294862.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p662783p678431.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p662783p678431.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p662783p678431.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2902894p2945098.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history10.xml-p2902894p2945098.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history10.xml-p2902894p2945098.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p872911p889148.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history6.xml-p872911p889148.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history6.xml-p872911p889148.bz2" && \
echo "Successful." && exit 0
echo "Error downloading." && exit 1

