#!/bin/bash
# This script autogenerated by DownloadEnwikiDump.ipynb

echo "Starting download." && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p496375p509555.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p496375p509555.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p496375p509555.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p391884p401697.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p391884p401697.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p391884p401697.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p509556p523148.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p509556p523148.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p509556p523148.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p401698p409337.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p401698p409337.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p401698p409337.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p366463p374744.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p366463p374744.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p366463p374744.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p360337p366462.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p360337p366462.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p360337p366462.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p536766p552239.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p536766p552239.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p536766p552239.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p374745p381686.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p374745p381686.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p374745p381686.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p552240p564696.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p552240p564696.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p552240p564696.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p462026p473695.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p462026p473695.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p462026p473695.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p473696p485186.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p473696p485186.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p473696p485186.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p453243p462025.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p453243p462025.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p453243p462025.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p409338p416289.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p409338p416289.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p409338p416289.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p485187p496374.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p485187p496374.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p485187p496374.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p424417p431455.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p424417p431455.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p424417p431455.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p352690p360336.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p352690p360336.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p352690p360336.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p564697p565313.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p564697p565313.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p564697p565313.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p416290p424416.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p416290p424416.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p416290p424416.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p447298p453242.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p447298p453242.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p447298p453242.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p381687p391883.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p381687p391883.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p381687p391883.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p523149p536765.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p523149p536765.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p523149p536765.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p431456p438866.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p431456p438866.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p431456p438866.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p438867p447297.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history5.xml-p438867p447297.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history5.xml-p438867p447297.bz2" && \
echo "Successful." && exit 0
echo "Error downloading." && exit 1

