#!/bin/bash
# This script autogenerated by DownloadEnwikiDump.ipynb

echo "Starting download." && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3307412p3356442.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3307412p3356442.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3307412p3356442.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4439111p4498533.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4439111p4498533.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4439111p4498533.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11189897p11283086.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11189897p11283086.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11189897p11283086.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15164053p15295537.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15164053p15295537.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15164053p15295537.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5133163p5137199.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5133163p5137199.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5133163p5137199.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7535778p7617410.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7535778p7617410.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7535778p7617410.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10267165p10386347.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10267165p10386347.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10267165p10386347.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14767172p14901427.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14767172p14901427.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14767172p14901427.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5740889p5801865.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5740889p5801865.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5740889p5801865.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4920616p4987446.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4920616p4987446.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4920616p4987446.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8574934p8660548.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8574934p8660548.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8574934p8660548.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14377952p14513898.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14377952p14513898.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14377952p14513898.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18863533p18951364.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p18863533p18951364.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18863533p18951364.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p3986257p4044135.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p3986257p4044135.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p3986257p4044135.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15421659p15546010.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15421659p15546010.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15421659p15546010.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10386348p10483941.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10386348p10483941.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10386348p10483941.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11768711p11883792.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p11768711p11883792.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11768711p11883792.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11651733p11768710.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p11651733p11768710.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11651733p11768710.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5138122p5144179.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5138122p5144179.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5138122p5144179.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6507794p6589055.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6507794p6589055.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6507794p6589055.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5148851p5149044.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5148851p5149044.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5148851p5149044.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4102042p4157943.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4102042p4157943.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4102042p4157943.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16987718p17141817.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16987718p17141817.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16987718p17141817.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4211295p4267166.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4211295p4267166.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4211295p4267166.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7452071p7535777.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7452071p7535777.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7452071p7535777.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9098179p9204411.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p9098179p9204411.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9098179p9204411.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7708628p7744799.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7708628p7744799.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7708628p7744799.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5484142p5551652.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5484142p5551652.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5484142p5551652.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8838218p8929318.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8838218p8929318.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8838218p8929318.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17578402p17719754.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17578402p17719754.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17578402p17719754.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6272328p6349417.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6272328p6349417.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6272328p6349417.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13833638p13969998.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p13833638p13969998.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13833638p13969998.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11411589p11424849.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11411589p11424849.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11411589p11424849.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3248899p3263900.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3248899p3263900.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3248899p3263900.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149099p5149128.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5149099p5149128.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149099p5149128.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10051073p10153682.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10051073p10153682.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10051073p10153682.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4782255p4854242.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4782255p4854242.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4782255p4854242.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8485952p8574933.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8485952p8574933.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8485952p8574933.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13227960p13353280.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13227960p13353280.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13227960p13353280.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9515020p9518048.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p9515020p9518048.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9515020p9518048.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3523148p3566423.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3523148p3566423.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3523148p3566423.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4383714p4439110.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4383714p4439110.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4383714p4439110.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7095655p7177833.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7095655p7177833.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7095655p7177833.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13969999p14111892.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p13969999p14111892.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13969999p14111892.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6197598p6272327.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6197598p6272327.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6197598p6272327.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5144180p5147312.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5144180p5147312.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5144180p5147312.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8009372p8107719.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8009372p8107719.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8009372p8107719.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3263901p3307411.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3263901p3307411.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3263901p3307411.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6742712p6794355.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6742712p6794355.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6742712p6794355.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8287255p8387127.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8287255p8387127.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8287255p8387127.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11283087p11398199.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11283087p11398199.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11283087p11398199.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20483046p20614811.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20483046p20614811.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20483046p20614811.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6866649p6929298.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6866649p6929298.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6866649p6929298.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3445662p3491925.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3445662p3491925.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3445662p3491925.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16278351p16356093.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16278351p16356093.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16278351p16356093.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10689832p10795617.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10689832p10795617.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10689832p10795617.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8997642p9098178.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8997642p9098178.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8997642p9098178.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13182422p13227959.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13182422p13227959.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13182422p13227959.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20986075p21099376.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20986075p21099376.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20986075p21099376.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4610967p4663881.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4610967p4663881.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4610967p4663881.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8387128p8485951.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8387128p8485951.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8387128p8485951.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4157944p4211294.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4157944p4211294.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4157944p4211294.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4663882p4723675.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4663882p4723675.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4663882p4723675.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5551653p5613012.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5551653p5613012.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5551653p5613012.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3046514p3090639.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3046514p3090639.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3046514p3090639.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5147313p5148850.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5147313p5148850.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5147313p5148850.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p21099377p21222156.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p21099377p21222156.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p21099377p21222156.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6794356p6866648.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6794356p6866648.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6794356p6866648.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19629460p19715587.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19629460p19715587.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19629460p19715587.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18754736p18863532.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p18754736p18863532.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18754736p18863532.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3706875p3729248.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3706875p3729248.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3706875p3729248.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13148375p13182421.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13148375p13182421.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13148375p13182421.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8751072p8838217.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8751072p8838217.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8751072p8838217.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14513899p14641023.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14513899p14641023.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14513899p14641023.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5987631p6047478.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5987631p6047478.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5987631p6047478.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6589056p6677188.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6589056p6677188.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6589056p6677188.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8200456p8287254.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8200456p8287254.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8200456p8287254.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16356094p16526333.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16356094p16526333.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16356094p16526333.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18311357p18444653.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18311357p18444653.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18311357p18444653.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7744803p7832207.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p7744803p7832207.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7744803p7832207.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3869280p3926861.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3869280p3926861.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3869280p3926861.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10574194p10689831.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10574194p10689831.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10574194p10689831.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20306333p20483045.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20306333p20483045.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20306333p20483045.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4723676p4782254.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4723676p4782254.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4723676p4782254.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16526334p16704255.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16526334p16704255.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16526334p16704255.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20755443p20869974.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20755443p20869974.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20755443p20869974.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5040438p5068893.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5040438p5068893.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5040438p5068893.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6047479p6115976.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p6047479p6115976.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6047479p6115976.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7177834p7270657.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7177834p7270657.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7177834p7270657.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12302530p12413430.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12302530p12413430.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12302530p12413430.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7270658p7365781.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7270658p7365781.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7270658p7365781.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12851489p12960768.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12851489p12960768.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12851489p12960768.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15915958p16044075.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15915958p16044075.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15915958p16044075.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19849380p19994760.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19849380p19994760.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19849380p19994760.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3090640p3134329.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3090640p3134329.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3090640p3134329.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6115977p6181822.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p6115977p6181822.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6115977p6181822.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3356443p3407399.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3356443p3407399.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3356443p3407399.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18951365p19024196.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p18951365p19024196.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p18951365p19024196.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3613623p3655893.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3613623p3655893.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3613623p3655893.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10795618p10912697.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10795618p10912697.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10795618p10912697.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5414973p5484141.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5414973p5484141.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5414973p5484141.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9735727p9853242.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p9735727p9853242.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9735727p9853242.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3491926p3523147.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3491926p3523147.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3491926p3523147.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5068894p5133162.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5068894p5133162.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5068894p5133162.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14249599p14377951.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14249599p14377951.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14249599p14377951.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5342737p5414972.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5342737p5414972.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5342737p5414972.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11398200p11411588.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11398200p11411588.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11398200p11411588.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4987447p5040436.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4987447p5040436.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4987447p5040436.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16926189p16987717.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16926189p16987717.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16926189p16987717.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5137200p5137386.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5137200p5137386.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5137200p5137386.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6428460p6507793.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6428460p6507793.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6428460p6507793.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15031000p15164052.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15031000p15164052.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15031000p15164052.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10153683p10267164.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10153683p10267164.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10153683p10267164.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4498534p4552935.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4498534p4552935.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4498534p4552935.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3761823p3816330.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3761823p3816330.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3761823p3816330.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11539268p11651732.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p11539268p11651732.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11539268p11651732.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18689470p18754735.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18689470p18754735.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18689470p18754735.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18160995p18311356.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18160995p18311356.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18160995p18311356.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19269029p19373092.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19269029p19373092.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19269029p19373092.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p16044076p16120542.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p16044076p16120542.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p16044076p16120542.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3407400p3445661.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3407400p3445661.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3407400p3445661.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7617411p7708627.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7617411p7708627.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7617411p7708627.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7010656p7095654.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7010656p7095654.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7010656p7095654.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3655894p3706874.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3655894p3706874.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3655894p3706874.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9936334p10051072.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p9936334p10051072.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9936334p10051072.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5801866p5862535.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5801866p5862535.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5801866p5862535.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3224869p3248898.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3224869p3248898.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3224869p3248898.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p3926863p3986256.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p3926863p3986256.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p3926863p3986256.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5210961p5278959.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5210961p5278959.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5210961p5278959.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149045p5149098.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5149045p5149098.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149045p5149098.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17719755p17860588.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17719755p17860588.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17719755p17860588.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12086933p12191274.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12086933p12191274.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12086933p12191274.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20869975p20986074.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20869975p20986074.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20869975p20986074.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16842096p16926188.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16842096p16926188.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16842096p16926188.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12191275p12302529.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12191275p12302529.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12191275p12302529.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4267167p4324932.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4267167p4324932.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4267167p4324932.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11883793p11989289.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p11883793p11989289.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11883793p11989289.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7365782p7452070.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p7365782p7452070.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p7365782p7452070.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12744043p12851488.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12744043p12851488.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12744043p12851488.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3180488p3224868.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3180488p3224868.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3180488p3224868.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15295538p15421658.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15295538p15421658.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15295538p15421658.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5278960p5342736.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5278960p5342736.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5278960p5342736.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6929299p7010655.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6929299p7010655.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6929299p7010655.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19505726p19629459.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19505726p19629459.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19505726p19629459.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17860589p18008302.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17860589p18008302.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17860589p18008302.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3729249p3761822.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3729249p3761822.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3729249p3761822.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16704256p16842095.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16704256p16842095.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16704256p16842095.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10912698p11009159.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10912698p11009159.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10912698p11009159.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5137387p5138121.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5137387p5138121.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5137387p5138121.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11424850p11436861.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11424850p11436861.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11424850p11436861.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16120543p16278350.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p16120543p16278350.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p16120543p16278350.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7832208p7924010.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p7832208p7924010.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7832208p7924010.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19373093p19505725.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19373093p19505725.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19373093p19505725.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14111893p14249598.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14111893p14249598.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14111893p14249598.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3134330p3180487.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3134330p3180487.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3134330p3180487.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20614812p20755442.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20614812p20755442.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20614812p20755442.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20137118p20306332.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p20137118p20306332.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p20137118p20306332.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18008303p18160994.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18008303p18160994.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18008303p18160994.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9623053p9735726.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p9623053p9735726.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9623053p9735726.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13353281p13471616.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13353281p13471616.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13353281p13471616.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9415097p9515019.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p9415097p9515019.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9415097p9515019.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17422281p17578401.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17422281p17578401.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17422281p17578401.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4854243p4920615.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4854243p4920615.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4854243p4920615.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6677189p6742711.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6677189p6742711.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6677189p6742711.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9204412p9306113.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p9204412p9306113.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9204412p9306113.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13055299p13148374.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13055299p13148374.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13055299p13148374.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11436862p11539266.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11436862p11539266.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11436862p11539266.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9518050p9623052.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p9518050p9623052.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9518050p9623052.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5680735p5740888.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5680735p5740888.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5680735p5740888.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18580817p18689469.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18580817p18689469.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18580817p18689469.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6349418p6428459.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history14.xml-p6349418p6428459.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history14.xml-p6349418p6428459.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17276776p17422280.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17276776p17422280.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17276776p17422280.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17141818p17276775.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p17141818p17276775.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p17141818p17276775.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7924011p8009371.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p7924011p8009371.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p7924011p8009371.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5862536p5928501.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5862536p5928501.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5862536p5928501.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8929319p8997641.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8929319p8997641.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8929319p8997641.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12519623p12626625.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12519623p12626625.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12519623p12626625.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5613013p5680734.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5613013p5680734.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5613013p5680734.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19715588p19849379.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19715588p19849379.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19715588p19849379.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9853243p9936333.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p9853243p9936333.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p9853243p9936333.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19994761p20137117.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19994761p20137117.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19994761p20137117.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5928502p5987630.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5928502p5987630.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5928502p5987630.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15672392p15793529.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15672392p15793529.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15672392p15793529.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4552936p4610966.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4552936p4610966.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4552936p4610966.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6181823p6197594.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p6181823p6197594.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p6181823p6197594.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9306114p9415096.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p9306114p9415096.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p9306114p9415096.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11989290p12086932.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p11989290p12086932.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p11989290p12086932.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11083604p11189896.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11083604p11189896.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11083604p11189896.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3566424p3613622.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3566424p3613622.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3566424p3613622.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10483942p10574193.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p10483942p10574193.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p10483942p10574193.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12960769p13055298.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12960769p13055298.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12960769p13055298.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14901428p15030999.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14901428p15030999.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14901428p15030999.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18444654p18530376.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18444654p18530376.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18444654p18530376.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13471617p13600299.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13471617p13600299.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13471617p13600299.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15793530p15915957.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15793530p15915957.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15793530p15915957.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19024197p19156567.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19024197p19156567.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19024197p19156567.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4324933p4383713.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4324933p4383713.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4324933p4383713.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8107720p8200455.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8107720p8200455.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8107720p8200455.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13693074p13784397.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p13693074p13784397.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13693074p13784397.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12626626p12744042.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12626626p12744042.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12626626p12744042.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13784398p13833637.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p13784398p13833637.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p13784398p13833637.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13600300p13693071.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p13600300p13693071.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p13600300p13693071.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19156568p19269028.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history20.xml-p19156568p19269028.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history20.xml-p19156568p19269028.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14641024p14767171.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p14641024p14767171.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p14641024p14767171.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149129p5210960.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history13.xml-p5149129p5210960.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history13.xml-p5149129p5210960.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4044136p4102041.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history12.xml-p4044136p4102041.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history12.xml-p4044136p4102041.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12413431p12519622.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history17.xml-p12413431p12519622.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history17.xml-p12413431p12519622.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8660549p8751071.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history15.xml-p8660549p8751071.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history15.xml-p8660549p8751071.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15546011p15672391.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history18.xml-p15546011p15672391.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history18.xml-p15546011p15672391.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18530377p18580816.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history19.xml-p18530377p18580816.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history19.xml-p18530377p18580816.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3816331p3869279.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history11.xml-p3816331p3869279.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history11.xml-p3816331p3869279.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11009160p11083603.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history16.xml-p11009160p11083603.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history16.xml-p11009160p11083603.bz2" && \
echo "Successful." && exit 0
echo "Error downloading." && exit 1

