#!/bin/bash
# This script autogenerated by DownloadEnwikiDump.ipynb

echo "Starting download." && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24195688p24344788.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24195688p24344788.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24195688p24344788.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41245377p41460445.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p41245377p41460445.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41245377p41460445.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21476679p21608305.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21476679p21608305.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21476679p21608305.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25683995p25702518.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25683995p25702518.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25683995p25702518.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32098248p32205318.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32098248p32205318.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32098248p32205318.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42097259p42303666.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p42097259p42303666.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42097259p42303666.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47501393p47714333.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p47501393p47714333.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47501393p47714333.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31748523p31855872.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31748523p31855872.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31748523p31855872.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23394691p23501897.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23394691p23501897.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23394691p23501897.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22887823p23040283.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22887823p23040283.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22887823p23040283.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50048594p50362754.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p50048594p50362754.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50048594p50362754.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29230749p29432795.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p29230749p29432795.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29230749p29432795.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33704202p33896245.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p33704202p33896245.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33704202p33896245.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50362755p50632640.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p50362755p50632640.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50362755p50632640.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46861209p47073665.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p46861209p47073665.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46861209p47073665.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41460446p41667597.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p41460446p41667597.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41460446p41667597.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43001066p43202762.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43001066p43202762.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43001066p43202762.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47288335p47501392.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p47288335p47501392.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47288335p47501392.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52146180p52391424.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p52146180p52391424.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52146180p52391424.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22042258p22181560.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22042258p22181560.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22042258p22181560.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56531498p56850723.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p56531498p56850723.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56531498p56850723.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55638215p55926920.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p55638215p55926920.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55638215p55926920.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38671318p38877865.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p38671318p38877865.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38671318p38877865.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27505780p27644558.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27505780p27644558.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27505780p27644558.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46503670p46678815.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p46503670p46678815.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46503670p46678815.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52391425p52656030.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p52391425p52656030.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52391425p52656030.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60863860p61290155.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p60863860p61290155.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60863860p61290155.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48462119p48701137.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p48462119p48701137.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48462119p48701137.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p23927984p24061330.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p23927984p24061330.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p23927984p24061330.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35981623p36171035.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p35981623p36171035.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35981623p36171035.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37874531p38063768.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p37874531p38063768.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37874531p38063768.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33332538p33525351.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p33332538p33525351.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33332538p33525351.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p61706024p62176946.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p61706024p62176946.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p61706024p62176946.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36359913p36511636.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p36359913p36511636.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36359913p36511636.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23624363p23767055.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23624363p23767055.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23624363p23767055.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39649639p39851628.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p39649639p39851628.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39649639p39851628.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36680260p36858454.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p36680260p36858454.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36680260p36858454.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23187075p23283926.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23187075p23283926.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23187075p23283926.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40266361p40481695.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p40266361p40481695.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40266361p40481695.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32002207p32098247.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32002207p32098247.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32002207p32098247.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37477766p37674341.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p37477766p37674341.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37477766p37674341.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35403898p35618048.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p35403898p35618048.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35403898p35618048.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23903813p23927983.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23903813p23927983.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23903813p23927983.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34797621p34985658.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34797621p34985658.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34797621p34985658.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45164690p45370843.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p45164690p45370843.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45164690p45370843.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33142875p33332537.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p33142875p33332537.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33142875p33332537.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22465523p22612987.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22465523p22612987.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22465523p22612987.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29029261p29230748.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p29029261p29230748.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29029261p29230748.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26821360p26823660.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26821360p26823660.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26821360p26823660.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40068801p40266360.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p40068801p40266360.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40068801p40266360.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30859469p30932054.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p30859469p30932054.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30859469p30932054.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50632641p50901685.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p50632641p50901685.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50632641p50901685.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52925066p53213823.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p52925066p53213823.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52925066p53213823.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25558941p25683994.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25558941p25683994.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25558941p25683994.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27345129p27505779.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27345129p27505779.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27345129p27505779.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27952884p28102815.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27952884p28102815.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27952884p28102815.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44199865p44410398.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p44199865p44410398.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44199865p44410398.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28682142p28859171.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p28682142p28859171.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28682142p28859171.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49452600p49741667.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p49452600p49741667.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49452600p49741667.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37045552p37258608.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p37045552p37258608.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37045552p37258608.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44912142p45164689.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p44912142p45164689.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44912142p45164689.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48701138p48938358.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p48701138p48938358.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48701138p48938358.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31855873p32002206.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31855873p32002206.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31855873p32002206.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35174143p35403897.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p35174143p35403897.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35174143p35403897.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53798906p54059258.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p53798906p54059258.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53798906p54059258.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48196825p48462118.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p48196825p48462118.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48196825p48462118.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60065440p60458203.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p60065440p60458203.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60065440p60458203.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33525352p33704201.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p33525352p33704201.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33525352p33704201.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25238960p25404127.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25238960p25404127.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25238960p25404127.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22747300p22887822.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22747300p22887822.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22747300p22887822.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36858455p37045551.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p36858455p37045551.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36858455p37045551.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38067203p38267452.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p38067203p38267452.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38067203p38267452.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p33952816p34140532.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p33952816p34140532.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p33952816p34140532.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47714334p47909193.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p47714334p47909193.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47714334p47909193.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36171036p36359912.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p36171036p36359912.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36171036p36359912.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p59673767p60065439.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p59673767p60065439.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p59673767p60065439.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49741668p50048593.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p49741668p50048593.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49741668p50048593.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23501898p23624362.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23501898p23624362.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23501898p23624362.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32391814p32579873.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32391814p32579873.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32391814p32579873.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24783430p24952747.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24783430p24952747.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24783430p24952747.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28102816p28265697.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p28102816p28265697.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28102816p28265697.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57801700p58121660.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p57801700p58121660.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57801700p58121660.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p62176947p62717971.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p62176947p62717971.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p62176947p62717971.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31458718p31588155.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31458718p31588155.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31458718p31588155.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p26996673p27168186.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p26996673p27168186.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p26996673p27168186.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56218616p56531497.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p56218616p56531497.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56218616p56531497.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24489144p24626749.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24489144p24626749.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24489144p24626749.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24626750p24783429.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24626750p24783429.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24626750p24783429.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33896246p33952815.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p33896246p33952815.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p33896246p33952815.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36511637p36680259.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p36511637p36680259.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p36511637p36680259.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28859172p29029260.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p28859172p29029260.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28859172p29029260.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34492599p34677028.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34492599p34677028.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34492599p34677028.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48938359p49181577.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p48938359p49181577.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p48938359p49181577.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27168187p27345128.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27168187p27345128.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27168187p27345128.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25404128p25558940.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25404128p25558940.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25404128p25558940.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31275195p31458717.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31275195p31458717.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31275195p31458717.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57476307p57801699.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p57476307p57801699.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57476307p57801699.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27644559p27774519.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27644559p27774519.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27644559p27774519.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21898839p22042257.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21898839p22042257.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21898839p22042257.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43989292p44199864.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43989292p44199864.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43989292p44199864.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45953838p46298694.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p45953838p46298694.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45953838p46298694.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42521994p42663461.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p42521994p42663461.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42521994p42663461.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23767056p23903812.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23767056p23903812.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23767056p23903812.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40481696p40698539.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p40481696p40698539.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40481696p40698539.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30014519p30211772.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p30014519p30211772.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30014519p30211772.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38877866p39083787.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p38877866p39083787.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38877866p39083787.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42303667p42521993.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p42303667p42521993.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p42303667p42521993.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54981506p55312843.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p54981506p55312843.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54981506p55312843.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49181578p49452599.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p49181578p49452599.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p49181578p49452599.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53520296p53798905.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p53520296p53798905.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53520296p53798905.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24061331p24195687.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24061331p24195687.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24061331p24195687.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41885992p42097258.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p41885992p42097258.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41885992p42097258.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60458204p60863859.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p60458204p60863859.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p60458204p60863859.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40907590p41063866.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p40907590p41063866.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40907590p41063866.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35618049p35807270.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p35618049p35807270.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35618049p35807270.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51395199p51667488.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p51395199p51667488.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51395199p51667488.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45601055p45953837.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p45601055p45953837.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45601055p45953837.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32579874p32766243.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32579874p32766243.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32579874p32766243.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26180067p26332536.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26180067p26332536.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26180067p26332536.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54318555p54619999.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p54318555p54619999.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54318555p54619999.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26011530p26180066.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26011530p26180066.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26011530p26180066.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43412138p43592481.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43412138p43592481.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43412138p43592481.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22319882p22465522.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22319882p22465522.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22319882p22465522.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58525635p58898845.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p58525635p58898845.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58525635p58898845.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51143358p51395198.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p51143358p51395198.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51143358p51395198.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43592482p43768592.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43592482p43768592.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43592482p43768592.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30503451p30703299.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p30503451p30703299.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30503451p30703299.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43768593p43989291.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43768593p43989291.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43768593p43989291.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32205319p32391813.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32205319p32391813.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32205319p32391813.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47073666p47288334.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p47073666p47288334.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47073666p47288334.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p26823661p26996672.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p26823661p26996672.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p26823661p26996672.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50901686p51143357.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p50901686p51143357.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p50901686p51143357.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30409488p30503449.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p30409488p30503449.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30409488p30503449.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23283927p23394690.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23283927p23394690.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23283927p23394690.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54620000p54981505.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p54620000p54981505.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54620000p54981505.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22181561p22319881.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22181561p22319881.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22181561p22319881.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45370844p45601054.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p45370844p45601054.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p45370844p45601054.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55926921p56218615.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p55926921p56218615.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55926921p56218615.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23040284p23187074.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p23040284p23187074.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p23040284p23187074.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28265698p28435480.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p28265698p28435480.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28265698p28435480.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55312844p55638214.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p55312844p55638214.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p55312844p55638214.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31099380p31275194.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31099380p31275194.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31099380p31275194.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30703300p30859468.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p30703300p30859468.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30703300p30859468.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39083788p39280833.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p39083788p39280833.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39083788p39280833.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46298695p46503669.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p46298695p46503669.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46298695p46503669.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32961391p33142874.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32961391p33142874.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32961391p33142874.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p38063769p38067202.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p38063769p38067202.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p38063769p38067202.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34677029p34797620.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34677029p34797620.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34677029p34797620.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39280834p39462619.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p39280834p39462619.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39280834p39462619.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30211773p30409487.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p30211773p30409487.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p30211773p30409487.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29828381p30014518.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p29828381p30014518.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29828381p30014518.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32766244p32961390.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p32766244p32961390.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p32766244p32961390.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28435481p28682141.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p28435481p28682141.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p28435481p28682141.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25702519p25856656.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25702519p25856656.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25702519p25856656.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34985659p35174142.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34985659p35174142.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34985659p35174142.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51667489p51995346.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p51667489p51995346.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51667489p51995346.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38267453p38464941.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p38267453p38464941.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38267453p38464941.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21348264p21476678.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21348264p21476678.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21348264p21476678.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47909194p48196824.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p47909194p48196824.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p47909194p48196824.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39851629p40068800.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p39851629p40068800.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39851629p40068800.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25100393p25238959.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25100393p25238959.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25100393p25238959.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29610274p29828380.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p29610274p29828380.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29610274p29828380.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54059259p54318554.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p54059259p54318554.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p54059259p54318554.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35807271p35981622.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p35807271p35981622.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p35807271p35981622.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52656031p52925065.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p52656031p52925065.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p52656031p52925065.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46678816p46861208.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p46678816p46861208.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p46678816p46861208.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34140533p34307268.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34140533p34307268.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34140533p34307268.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24344789p24489143.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24344789p24489143.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24344789p24489143.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34307269p34492598.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p34307269p34492598.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p34307269p34492598.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41667598p41885991.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p41667598p41885991.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41667598p41885991.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40698540p40907589.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p40698540p40907589.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p40698540p40907589.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21608306p21756191.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21608306p21756191.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21608306p21756191.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21756192p21898838.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21756192p21898838.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21756192p21898838.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53213824p53520295.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p53213824p53520295.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p53213824p53520295.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58898846p59310037.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p58898846p59310037.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58898846p59310037.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26498368p26657878.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26498368p26657878.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26498368p26657878.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38464942p38671317.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p38464942p38671317.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p38464942p38671317.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25856657p26011529.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p25856657p26011529.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p25856657p26011529.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43202763p43412137.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p43202763p43412137.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p43202763p43412137.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57166577p57476306.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p57166577p57476306.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p57166577p57476306.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56850724p57166576.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p56850724p57166576.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p56850724p57166576.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p59310038p59673766.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p59310038p59673766.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p59310038p59673766.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26332537p26498367.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26332537p26498367.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26332537p26498367.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37674342p37874530.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p37674342p37874530.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37674342p37874530.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44410399p44651760.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p44410399p44651760.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44410399p44651760.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51995347p52146179.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p51995347p52146179.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p51995347p52146179.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26657879p26821359.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p26657879p26821359.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p26657879p26821359.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39462620p39649638.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p39462620p39649638.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p39462620p39649638.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p61290156p61706023.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p61290156p61706023.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p61290156p61706023.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30932055p31099379.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p30932055p31099379.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p30932055p31099379.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p42780990p43001065.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p42780990p43001065.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p42780990p43001065.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58121661p58525634.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p58121661p58525634.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p58121661p58525634.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p42663462p42780989.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p42663462p42780989.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p42663462p42780989.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31588156p31748522.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history24.xml-p31588156p31748522.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history24.xml-p31588156p31748522.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44651761p44912141.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history27.xml-p44651761p44912141.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history27.xml-p44651761p44912141.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24952748p25100392.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history22.xml-p24952748p25100392.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history22.xml-p24952748p25100392.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22612988p22747299.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p22612988p22747299.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p22612988p22747299.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27774520p27952883.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p27774520p27952883.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p27774520p27952883.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41063867p41245376.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history26.xml-p41063867p41245376.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history26.xml-p41063867p41245376.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37258609p37477765.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history25.xml-p37258609p37477765.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history25.xml-p37258609p37477765.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21222158p21348263.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history21.xml-p21222158p21348263.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history21.xml-p21222158p21348263.bz2" && \
echo "Downloading '/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29432796p29610273.bz2'." && \
wget --no-check-certificate -nc -O /export/scratch2/wiki_data/enwiki-20200101-pages-meta-history-bz2/enwiki-20200101-pages-meta-history23.xml-p29432796p29610273.bz2 "https://dumps.wikimedia.org/enwiki/20200101/enwiki-20200101-pages-meta-history23.xml-p29432796p29610273.bz2" && \
echo "Successful." && exit 0
echo "Error downloading." && exit 1

